@startuml
'https://plantuml.com/class-diagram

class MusicHelper {
    -static final String TAG
    -final int[] musicIndex
    -int currentIndex
    -Context mContext
    -MediaPlayer mediaPlayer
    --
    +create(Context context): void
    +destroy(): void
    +getPosition(): int
    +playSong(int index): void
    +pause(): void
}

@enduml